name: Build and pack nightly

on:
  push:
      branches:
        - nightly

jobs:
    pack-nightly:
      env:
        DOTNET_INSTALL_DIR: ".dotnet"

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Get date for version
          id: date
          run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
        # setup .NET per the repo global.json
        - name: Setup .NET
          uses: actions/setup-dotnet@v2

        - name: Restore tools
          run: dotnet tool restore

        - name: Run Build
          run: dotnet pack -c Release -o bin
          env:
            VersionSuffix: "beta${{ steps.date.outputs.date }}"
            BuildNet7: ${{ env.BuildNet7 }}

        - name: Push packages
          run: dotnet nuget push bin/fsautocomplete.*.nupkg --source https://nuget.pkg.github.com/fsharp/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
