name: update nightly FCS

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  bump-fcs:
    name: bump FCS to latest nightly
    runs-on: ubuntu-latest

    env:
        DOTNET_INSTALL_DIR: ".dotnet"

    steps:
      - name: checkout nightly branch
        uses: actions/checkout@v3
        with:
          ref: nightly
          # using a custom token instead of GITHUB_TOKEN allows other workflows to trigger as a result of the push
          token: ${{ secrets.FCS_NIGHTLY_UPDATE_TOKEN }}
      - name: configure .NET
        uses: actions/setup-dotnet@v2
      - name: restore tools
        run: dotnet tool restore
      - name: bump FCS
        run: dotnet paket update FSharp.Compiler.Service
      - name: check if there are changes
        continue-on-error: true # nonzero exit codes are expected if there are changes
        id: check
        run: |
          git diff --exit-code
          if [ $? -eq 0 ]; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi
      - name: commit changes
        if: steps.check.outputs.changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add paket.lock
          git commit -m "updated FCS to the latest nightly"
          git push

